### ISSUE TITLE
Is the environment right? vllm 0.11.4

### ISSUE THREAD

**Issue by tianyumyum** [yule-BUAA/MergeLM#1]
ERROR: Ignored the following yanked versions: 0.2.1
ERROR: Could not find a version that satisfies the requirement vllm==0.11.4 (from versions: 0.0.1, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.2.0, 0.2.1.post1)
ERROR: No matching distribution found for vllm==0.11.4

您好，请问是笔误吗，如果是的话正确的适配版本应该是什么呢～

**Comment by tianyumyum** [comment]
0.1.4好像是OK的

**Comment by yule-BUAA** [comment]
感谢对我们工作的关注！

这个版本号的问题是笔误了，不好意思哈～

使用的正确版本号是0.1.4，已经在README中更新了^_^
