### ISSUE TITLE
Does this work with Encoder-Decoder models like T5?

### ISSUE THREAD

**Issue by Inc0mple** [yule-BUAA/MergeLM#11]
Hi, thanks for sharing this awesome work! Does this method work with Encoder-Decoder models such as T5 and its derivatives (Flan-T5, TK-Instruct etc.)?

**Comment by yule-BUAA** [comment]
Hi, 

Thanks for your kind words on our work!

I think DARE can also work on LMs with the encoder-decoder architecture as long as their parameter changed ranges are not so significant (e.g., less than 0.005 as we concluded in section 4.6).

Moreover, it is exciting that DARE has been successfully applied to [Stable Diffusion models](https://github.com/martyn/safetensors-merge-supermario) to generate images. This demonstrates its generalizability and also ensures its feasibility when applied to encoder-decoder models like T5.

You can modify our code to extend to the T5 series model as well and feel free to contact me if there are any further questions.

**Comment by yule-BUAA** [comment]
Close this issue now.

Please feel free to reopen it when there are any further questions.
