### ISSUE TITLE
WizardMath model embedding层维度问题。

### ISSUE THREAD

**Issue by sasgkhgw** [yule-BUAA/MergeLM#12]
WizardMath-7B-V1.0，WizardMath-13B-V1.0的embedding层维度是[32001,4096],LLAMA2的embedding层维度是[32000，4096]。
在做处理的时候是跳过了embedding层还是有其他处理吗？

**Comment by yule-BUAA** [comment]
对于SFT模型（例如WizardMath-7B-V1.0）和Pre-Trained的基座模型（例如LLAMA2），我们首先对其embedding的维度进行对齐（详见inference_llms_instruct_math_code.py代码[105行](https://github.com/yule-BUAA/MergeLM/blob/6cf67a0e31dab22598a1162f0e10ea985f525083/inference_llms_instruct_math_code.py#L105)至[126行](https://github.com/yule-BUAA/MergeLM/blob/6cf67a0e31dab22598a1162f0e10ea985f525083/inference_llms_instruct_math_code.py#L126)），而后再进行embedding的差值计算等操作。

**Comment by sasgkhgw** [comment]
好的，非常感谢！
