### ISSUE TITLE
The question about encoder-based model merge.

### ISSUE THREAD

**Issue by bestfleer** [yule-BUAA/MergeLM#13]
Hi, thanks for your outstanding work on the model merging. I find that you only merge two tasks weights from glue in merge_plms_glue.py     
Can DARE merge all eight tasks weights into one model?

**Comment by yule-BUAA** [comment]
Hi,

Thanks for your interest in our work.

The setting of merging two tasks on encoder-based models follows existing methods like [Fisher Merging](https://arxiv.org/pdf/2111.09832.pdf) and [TIES Merging](https://arxiv.org/pdf/2306.01708.pdf). We also try to merge more than two tasks but the performance often gets worse, which is also observed in [TIES Merging](https://arxiv.org/pdf/2306.01708.pdf).

We also find that merging more than two decoder-based LLMs can often improve the performance (see Table 1 in our paper), indicating that decoder-based LLMs have more capacities than encoder-based LMs, and are more suitable for the model merging operation.

**Comment by yule-BUAA** [comment]
Close this issue now.

Please feel free to reopen it when there are any further questions.
