### ISSUE TITLE
为什么融合wizard-lm和math后模型生成乱码

### ISSUE THREAD

**Issue by anon6662** [yule-BUAA/MergeLM#14]
您好，我在复现这篇工作，我现在遇到了一个问题，我正常测评wizard-math没有问题，合并两个wizard-math也没有问题，但是不同任务的模型融合后，生成的respond就是乱码，（一个字符一直生成到最大长度），这可能是遇到了什么问题呢。我的模型是从huggingface 上wizrd项目下载的。

**Comment by yule-BUAA** [comment]
请问你在合并WizardLM和WizardMath使用的具体命令是什么呢？能否提供更详细的内容？

可以通过尝试运行最简单的average merging看下效果，我运行下面的命令合并WizardLM和WizardMath是没有问题的：
`python merge_llms_instruct_math_code.py --merge_instruct --merge_math --merging_method_name average_merging --tensor_parallel_size 1`
合并后的模型在AlpacaEval 指标为67.04，在GSM8K和MATH上的指标分别为66.34和13.40。

**Comment by anon6662** [comment]
感谢回复！我使用的是average merging，命令和你的一样。我检查了下代码和环境应该都没有问题，只是把merge_llms_instruct_math_code.py文件中的模型改成了我自己的路径。我现在怀疑我们所用的模型版本不太一样，我用的模型链接如下：
wizard_math: https://huggingface.co/WizardLM/WizardMath-13B-V1.0
wizard_lm: https://huggingface.co/WizardLM/WizardLM-13B-V1.1
llama13b: https://huggingface.co/meta-llama/Llama-2-13b-hf
其中wizard模型的嵌入层维度为32001，llama13b为32000。我观察代码对llama13b做了一个扩充处理。您看我的模型是否正确呢。
我又仔细看了下，WizardLM版本不一样，我换个版本再做实验试试

**Comment by yule-BUAA** [comment]
好的，换成WizardLM-13B-V1.2应该就没有问题了。
因为WizardLM-13B-V1.1的基模型为Llama 13B，而WizardLM-13B-V1.2的基模型为Llama 2 13B。后者与WizardMath-13B-V1.0使用的基模型一致。

**Comment by anon6662** [comment]
感谢！
