### ISSUE TITLE
你好，关于融合code模型的选择问题

### ISSUE THREAD

**Issue by anon6662** [yule-BUAA/MergeLM#15]
我注意到llama-2-13b-code-alpaca的代码能力不如wizard-lm, 所以尝试把代码模型换成WizardCoder-Python-13B-V1.0](https://huggingface.co/WizardLM/WizardCoder-Python-13B-V1.0)  ， 为何融合后的模型表现特别差。请问你们有做过类似尝试吗，有可能的原因吗

**Comment by yule-BUAA** [comment]
你好，

这是因为WizardCoder-Python-13B-V1.0是基于CodeLlama-13b-Python-hf微调而来的，而WizardLM-13B-V1.2是基于Llama-2-13b-hf微调得到的。这两者基于的backbone并不一样，无法直接用现有的方法完成合并，所以我们合并的是同样基于Llama-2-13b-hf微调得到的llama-2-13b-code-alpaca。
