### ISSUE TITLE
使用ties和magnitude方法遇到了一些问题

### ISSUE THREAD

**Issue by HypherX** [yule-BUAA/MergeLM#16]
作者您好，我在使用代码中的ties和magnitude这两种根据增量参数大小来筛选参数的方法时，得到的merged_model在推理阶段非常慢，而采用random的方法就不会出现这种情况，打印了模型参数也没发现没有加回到原预训练模型参数的情况，就都是有数值而不是大部分参数全都是0那种情况。而且同样筛选掉90%的增量参数，random能保持推理的效果几乎不变，但是ties和magnitude完全不会做下游任务了。不太清楚是什么问题。

**Comment by yule-BUAA** [comment]
嗨，

在根据增量参数大小来筛选参数时，是**不需要**rescale操作的， 即传入的命令中不设置`--use_weight_rescale`，例如
`python inference_llms_instruct_math_code.py --dataset_name gsm8k --finetuned_model_name WizardMath-7B-V1.0 --tensor_parallel_size 1 --weight_mask_rate 0.9 --mask_strategy magnitude`，这样可以保证下游任务表现不会太差。

我们的论文4.5节对基于magnitude的方法进行了比较，可以发现我们的random drop+rescale方法比基于magnitude的方法表现更好，尤其是在drop rate较高时（例如90%）。
