### ISSUE TITLE
 使用merge_llms_instruct_math_code.py在评估Math数据集的时候CUDA out of memory

### ISSUE THREAD

**Issue by RDXSun** [yule-BUAA/MergeLM#20]
如题，评估完alpaca后评估gsm8k就报错了
是因为创建的llm没有被成功释放吗

**Comment by yule-BUAA** [comment]
是的，可能引起OOM的错误是之前创建的模型没有被释放。

如果合并完WizardLM和WizardMath后出现这个错误，可以通过运行direct_inference_merged_llms_instruct_math_code.py对合并后的模型在instruction following（alpaca）和math（gsm8k和MATH）上分别进行评估。例如对使用average merging方法合并后的模型进行评测，可运行

```
python direct_inference_merged_llms_instruct_math_code.py --merge_instruct --merge_math --merging_method_name average_merging --tensor_parallel_size 1 --evaluate_task instruct
python direct_inference_merged_llms_instruct_math_code.py --merge_instruct --merge_math --merging_method_name average_merging --tensor_parallel_size 1 --evaluate_task math
```

**Comment by RDXSun** [comment]
sh

> 是的，可能引起OOM的错误是之前创建的模型没有被释放。
> 
> 如果合并完WizardLM和WizardMath后出现这个错误，可以通过运行direct_inference_merged_llms_instruct_math_code.py对合并后的模型在instruction following（alpaca）和math（gsm8k和MATH）上分别进行评估。例如对使用average merging方法合并后的模型进行评测，可运行
> 
> ```
> python direct_inference_merged_llms_instruct_math_code.py --merge_instruct --merge_math --merging_method_name average_merging --tensor_parallel_size 1 --evaluate_task instruct
> python direct_inference_merged_llms_instruct_math_code.py --merge_instruct --merge_math --merging_method_name average_merging --tensor_parallel_size 1 --evaluate_task math
> ```

好 谢谢
