### ISSUE TITLE
模型支持

### ISSUE THREAD

**Issue by clclclaiggg** [yule-BUAA/MergeLM#22]
您好，请问您的方法支持哪些模型呢，例如qwen或者[Mistral]吗

**Comment by yule-BUAA** [comment]
你好，
我们提出的方法可以应用于 Llama, Mistral, Qwen等多类模型。不过，现在的仓库代码中仅支持Llama模型。
如果你想尝试更多的模型，可以参考[mergekit](https://github.com/arcee-ai/mergekit)工具库，该工具库集成了我们提出的方法，并且更加高效地对多类现有LLM进行了支持。

**Comment by clclclaiggg** [comment]
明白了，谢谢



| |
cl15991441772
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Yu ***@***.***> |
| 发送日期 | 2024年3月12日 17:16 |
| 收件人 | ***@***.***> |
| 抄送人 | long ***@***.***> ,
***@***.***> |
| 主题 | Re: [yule-BUAA/MergeLM] 模型支持 (Issue #22) |

你好，
我们提出的方法可以应用于 Llama, Mistral, Qwen等多类模型。不过，现在的仓库代码中仅支持Llama模型。
如果你想尝试更多的模型，可以参考mergekit工具库，该工具库集成了我们提出的方法，并且更加高效地对多类现有LLM进行了支持。
