### ISSUE TITLE
Seeking mirrors of WizardLM models

### ISSUE THREAD

**Issue by Sophia118Guo** [yule-BUAA/MergeLM#27]
It seems that WizardLM has deleted all of their models. Could you help posting a few of the mirrors of these models, for example, WizardMath-13B-V1.0, WizardCoder-Python-13B-V1.0. Thank you very much!

**Comment by yule-BUAA** [comment]
Hello,

I have uploaded some Wizard-Series models on hugging face. Please see [here](https://huggingface.co/collections/vanillaOVO/wizard-models-667407fbde1698cc614c2565) to checkout the models.

**Comment by duguodong7** [comment]
Really appreciate！！

**Comment by Sophia118Guo** [comment]
Thank you so much!!!
