### ISSUE TITLE
Script to reproduce all experiment in paper

### ISSUE THREAD

**Issue by pkulium** [yule-BUAA/MergeLM#28]
great work! can we get Script to reproduce all experiment in paper?

**Comment by yule-BUAA** [comment]
Hello,

Apologies for the delay in my reply.

The main experiments in our paper consist of two parts:
1. verifying parameter redundancy via ```inference_plms_glue.py``` and ```inference_llms_instruct_math_code.py```; 
2. merging models via ```merge_plms_glue.py``` and ```merge_llms_instruct_math_code.py```. 
 
Following the guidelines outlined in README, you can reproduce the primary results in our paper. However, given the extensive experimental cases, it may be impractical to provide the scripts for all the experiments. Could you please specify which particular aspect you wish to reproduce but are uncertain about? This will enable me to offer more targeted assistance. 

Thank you!
