### ISSUE TITLE
是否可以Drop 100%？？？

### ISSUE THREAD

**Issue by Guozhenyuan** [yule-BUAA/MergeLM#30]
文中提到70B模型drop了99%delta参数依然保持了较高的性能。

有没有可能是因为70B模型在这个任务上已经十分出色，即使不微调也能够达到这么高的准确率（等同于drop100%）？

不知道作者有没有进行这方面实验验证？

如果看到这个issue，希望可以收到回复，感谢！！！

![Screenshot 2024-07-28 at 21 14 44](https://github.com/user-attachments/assets/e74b8aa6-149f-46b1-851c-dca4f1a308c0)

**Comment by yule-BUAA** [comment]
嗨，
    WizardMath-70B的基模型是Llama-2-70b，在[WizardMath论文](https://arxiv.org/pdf/2308.09583)的Figure 2中，Llama-2-70b在GSM8K的准确率为56.8，远低于WizardMath-70B的81.6。所以不微调的原始基模型的准确率并不高，而采用DARE后，仅需利用1%的delta参数便可取得和原始WizardMath相近的结果。

**Comment by Guozhenyuan** [comment]
感谢回复

DARE是非常有趣的工作，说明delta参数是稀疏的，大部分参数可能对任务不起作用，这给了我很大启发。

看到DARE进行的是随机Drop，我想知道这个结果的方差大概有多少呢？如果Drop掉了一些关键的delta参数会不会对结果影响很大？

**Comment by yule-BUAA** [comment]
感谢对我们工作的认可^_^

随机性的丢弃对于结果的影响并不大。在本仓库中，我们将随机种子设定为0以保证可复现性；我们也尝试过从1-9的seed，得到的结果同样相对稳定，我们认为random drop + rescale能够很好地维持模型每层的原始表征，因此保证了模型的性能。此外，还值得注意的是我们在论文中指出了DARE适用的delta参数变化范围（在0.002以内），较小的参数变化范围也是减少了random操作影响的因素之一。

**Comment by Guozhenyuan** [comment]
如果微调之后模型的delta参数变化范围<0.002的占比小于70%的话，最大的drop比例只能70%左右嘛？

rescale对于性能提升大概有多少呢?

**Comment by yule-BUAA** [comment]
drop的比例和delta参数变化范围<0.002的占比并没有明确的关系，对于所说的占比小于70%的情况，可以尝试依次递增的drop rate看下drop rate最大的设置是多少。

rescale对于DARE非常重要，如果不使用rescale，大部分情况下在drop rate达到0.3或者0.4时，模型的性能就会显著下降（可以参考论文的4.4节）

**Comment by Guozhenyuan** [comment]
感谢解答
