### ISSUE TITLE
Are the classification heads merged? 

### ISSUE THREAD

**Issue by yuang-lee** [yule-BUAA/MergeLM#31]
In your code, in case of merging BERT, Roberta, etc., It seems that the classification heads were not merged, but separately keep and add back to the merged checkpoints for each task. 
Am I correct?
Thanks!

**Comment by yule-BUAA** [comment]
Yes. Your understanding is right.

We do not merge the classification heads for BERT and Roberta since different tasks may have different numbers of classes.
