### ISSUE TITLE
Any solution to merge 3B models?

### ISSUE THREAD

**Issue by KADCA21** [yule-BUAA/MergeLM#32]

**Comment by yule-BUAA** [comment]
Hi,

The current repository is configured for merging 13B models only. For merging 3B models, you may consider the following two options:

1. Use [mergekit](https://github.com/arcee-ai/mergekit) to experiment with various merging methods.

2. Try our new repository [MergeLLM](https://github.com/yule-BUAA/MergeLLM) to merge your models.

Please be aware that the final merging results are influenced by the chosen method and hyperparameter settings. It is recommended to try multiple configurations to achieve satisfactory outcomes.
