### ISSUE TITLE
Alpaca_eval evaluation error

### ISSUE THREAD

**Issue by wang-kee** [yule-BUAA/MergeLM#33]
Hi, really impressive work! 

May I ask the following:

I got the following error when evaluating with Alpaca_eval using chatgpt_fn as suggested, but got the following error:

WARNING:root:OpenAIError: Error code: 404 - {'error': {'message': 'The model `gpt-3.5-turbo-16k-0613` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}.

It seems it is because chatgpt_fn uses `gpt-3.5-turbo-16k-0613` by default which has been deprecated as described. Do you recommend any alternative ways for evaluation? Thanks a lot in advance!

**Comment by yule-BUAA** [comment]
Hi,

Thanks for your interest in our work!

The `chatgpt_fn` model we used has been deprecated. I suggest using `alpaca_eval_gpt4` instead for evaluation on AlpacaEval. And I believe the observations from using `alpaca_eval_gpt4` would be similar to those from using `chatgpt_fn`.

If you have any questions during your further attempts, please feel free to ask.

**Comment by wang-kee** [comment]
Thanks a lot for your answer!
