### ISSUE TITLE
python enviornment

### ISSUE THREAD

**Issue by 1998v7** [yule-BUAA/MergeLM#35]
Dear author,

Thanks for your code. Could you please provide a requirement list for simply construct a python environment?

**Comment by yule-BUAA** [comment]
Hi,

Thank you for your interest in the code. Unfortunately, as this work was done during my internship and I no longer have access to the server to retrieve the specific environment details. However, based on the README file, you can set up a Python environment by installing the following main packages with their corresponding versions:
- PyTorch 2.0.1
- transformers 4.33.1
- datasets 2.13.1
- vllm 0.1.4
- human_eval
- numpy
- tqdm

Installing these packages should allow you to run and reproduce the results. If you encounter any missing packages during execution, you can install them as needed. 

Should you run into any issues, please feel free to reach out to me for further assistance.

**Comment by yule-BUAA** [comment]
Close this issue now.

Please feel free to reopen it when there are any further questions.

**Comment by harmlessSR** [comment]
Hi,
I'm trying to run your excellent code! However, when you require torch==2.0.1 and vllm==0.1.4, it seems that when I install vllm, it always requires to install torch==2.4.0 and this makes some trouble(I use cuda12.1). Did you meet the same problem? Or should I just ignore this?

By the way, though it may be out of scope for this issue, when I download WizardMath-7B-V1.0 from huggingface and run:

`python inference_llms_instruct_math_code.py --dataset_name gsm8k --finetuned_model_name WizardMath-7B-V1.0 --tensor_parallel_size 1 --weight_mask_rate 0.0`

I got:

`ValueError: Model architectures ['LlamaModel'] are not supported for now. Supported architectures: ['AquilaModel', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'FalconForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MPTForCausalLM', 'OPTForCausalLM', 'QWenLMHeadModel', 'RWForCausalLM']
`

as the architecture of WizardMath-7B-V1.0 is 'LlamaModel'. Do you have any thoughts about this problem?

Thanks a lot for your help!
