### ISSUE TITLE
Why same values of evaluation metrics when run>=1

### ISSUE THREAD

**Issue by zwxu064** [yule-BUAA/MergeLM#36]
Hi, I run the following in README.md,

    python train_plms_glue.py --language_model_name roberta-base --dataset_name cola --learning_rate 1e-5 --num_runs 5

The evaluation metrics including eval_loss and eval_matthews_correlation are exactly the same (including the best values and those at each epoch) when run={1,2,3,4}, although which is different from run=0. That is the best eval_loss and eval_matthews_correlation are the same when run=1,2,3,4.

![image](https://github.com/user-attachments/assets/a511f759-1d12-407b-b5cd-084eb394985d)

My understanding is: setting num_runs=5 is to get models with 5 different training initializations, each of which should have slightly different evaluation metrics when run varies, such that you can get an averaging for fair comparison. But the result is not from this code.

Is there any possibility that anything from run=0 after training is reserved and used for run>=1?

**Comment by yule-BUAA** [comment]
Hello,

We run five seeds to eliminate the randomness in training. However, your observation of identical metrics across different runs is something we have also encountered before.

Regarding your concern about the possibility of the results from run=0 being retained and used for run>=1, I assure you that this is not the case. In our [code](https://github.com/yule-BUAA/MergeLM/blob/6d49ad96fd69c92013654b837041b868aa806564/train_plms_glue.py#L45), each run is executed independently, ensuring that there is no interdependence between runs. Therefore, the observed consistency in evaluation metrics across different runs is unlikely to be influenced by the results of run=0.

The phenomenon you're witnessing might be specific to the dataset and model in use. It's possible that on other datasets, this consistency might not occur. Additionally, this phenomenon should not affect the training and selection of models, as the primary goal is to achieve robust performance across different initializations.

If you have any further questions, please don't hesitate to reach out.

**Comment by zwxu064** [comment]
Sure, that makes sense. I see the model is also loaded from the pretrained LLM within each run, so it should be ideally independent. Let's close this ticket. If I have further investigation, I will ping you then. Thank you.
