### ISSUE TITLE
Question about experimental settings

### ISSUE THREAD

**Issue by songjhPKU** [yule-BUAA/MergeLM#39]
Thanks for your work and DARE is really fantastic! I wonder what's the experimental settings for Dropout Rate for Decoder-Model Merging in Table 1 cause I did not find it in paper. Thanks for anwsering!

**Comment by yule-BUAA** [comment]
Hi,

We report the results in Table 1 by searching the scaling term of Task Arithmetic and TIES-Merging in [0.5, 1.0]. The retain ratio of largest-magnitude parameters in TIES-Merging is selected from [0.5, 0.7, 0.9]. Settings that achieve the best results are listed as follows. The drop rate of DARE is also included.

| Merging Methods |  Merging Models | AlpacaEval | GSM8K | MATH | HumanEval | MBPP |
|---------|---------|---------|---------|---------|---------|---------|
| Task Arithmetic  | LM & Math   | scaling term 1.0, drop rate 0.2  | scaling term 0.5, drop rate 0.6   |  scaling term 0.5, drop rate 0.6  |  scaling term 0.5, drop rate 0.6 | scaling term 0.5, drop rate 0.6 |
|   | LM & Code   | scaling term 1.0, drop rate 0.3   |  /  | /  | scaling term 1.0, drop rate 0.3  | scaling term 0.5, drop rate 0.4  |
|    | Math & Code  |  / | scaling term 1.0, drop rate 0.5   | scaling term 1.0, drop rate 0.5   | scaling term 0.5, drop rate 0.9   | scaling term 0.5, drop rate 0.9 |
|    | LM & Math & Code   | scaling term 1.0, drop rate 0.1   |  scaling term 0.5, drop rate 0.5   | scaling term 0.5, drop rate 0.5   | scaling term 0.5, drop rate 0.5   | scaling term 0.5, drop rate 0.5 |
| TIES-Merging  | LM & Math   | scaling term 1.0, retain ratio 0.5, drop rate 0.5  | scaling term 0.5, retain ratio 0.5, drop rate 0.5  |  scaling term 0.5, retain ratio 0.5, drop rate 0.5   |  scaling term 1.0, retain ratio 0.9, drop rate 0.1 | scaling term 1.0, retain ratio 0.9, drop rate 0.1  |
|   | LM & Code   | scaling term 1.0, retain ratio 0.5, drop rate 0.5    |   / |  / | scaling term 0.5, retain ratio 0.5, drop rate 0.5  | scaling term 1.0, retain ratio 0.5, drop rate 0.5  |
|    | Math & Code  | /  | scaling term 1.0, retain ratio 0.5, drop rate 0.5   | scaling term 1.0, retain ratio 0.5, drop rate 0.5   | scaling term 0.5, retain ratio 0.5, drop rate 0.5   | scaling term 0.5, retain ratio 0.7, drop rate 0.3 |
|    | LM & Math & Code   | scaling term 1.0, retain ratio 0.7, drop rate 0.3   |  scaling term 0.5, retain ratio 0.5, drop rate 0.5   | scaling term 0.5, retain ratio 0.5, drop rate 0.5   | scaling term 1.0, retain ratio 0.5, drop rate 0.5   | scaling term 0.5, retain ratio 0.5, drop rate 0.5 |

**Comment by daidaiershidi** [comment]
scaling term对应--scaling_coefficient，retain ratio对应weight_mask_rate对吗？

假如我想要得到表格中Task Arithmetic+Dare的

LM & Math & Code 
scaling term 1.0, drop rate 0.1

使用的命令为：python merge_llms_instruct_math_code.py --merge_instruct --merge_math --merge_code \
    --merging_method_name mask_merging \
    --mask_apply_method task_arithmetic \
    --weight_mask_rate 0.1 --use_weight_rescale --mask_strategy random \
    --scaling_coefficient 1.0 \
    --tensor_parallel_size 4 ;
   
这样对吗？

**Comment by daidaiershidi** [comment]
> Thanks for your work and DARE is really fantastic! I wonder what's the experimental settings for Dropout Rate for Decoder-Model Merging in Table 1 cause I did not find it in paper. Thanks for anwsering!

hi, have you successfully reproduced the results in the paper?

**Comment by yule-BUAA** [comment]
> scaling term对应--scaling_coefficient，retain ratio对应weight_mask_rate对吗？
> 
> 假如我想要得到表格中Task Arithmetic+Dare的
> 
> LM & Math & Code scaling term 1.0, drop rate 0.1
> 
> 使用的命令为：python merge_llms_instruct_math_code.py --merge_instruct --merge_math --merge_code --merging_method_name mask_merging --mask_apply_method task_arithmetic --weight_mask_rate 0.1 --use_weight_rescale --mask_strategy random --scaling_coefficient 1.0 --tensor_parallel_size 4 ;
> 
> 这样对吗？

1. 上面这条执行命令是对的。

2. scaling term对应scaling_coefficient，retain ratio是TIES-Merging需要设置的参数，对应 1 - param_value_mask_rate；而drop rate是DARE需要设置的参数，对应weight_mask_rate。

**Comment by KexuanShi** [comment]
这个上面的scaling coefficient是针对每个子任务模型设置的吗？
