### ISSUE TITLE
7B 模型合并问题

### ISSUE THREAD

**Issue by GarminQ** [yule-BUAA/MergeLM#41]
作者你好，是否可以合并WizardMath-7B-V1.0和WizardCoder-Python-7B-V1.0呢？
"WizardMath-7B-V1.0": "Llama-2-7b-hf",
"WizardCoder-Python-7B-V1.0": "Llama-2-7b-hf",

**Comment by yule-BUAA** [comment]
嗨，

WizardCoder-Python-7B-V1.0是基于Code Llama微调的。尽管Code Llama和Llama 2的结构相同，但是Code Llama又经过了大量token的continue pre-training，相较于Llama 2导致了极大的参数变化，而现在的merging方法并不适用于这种情况。我们的[另一篇工作](https://arxiv.org/abs/2408.03092)也指出了这个问题。

所以，简单地将WizardCoder-Python-7B-V1.0的backbone换成Llama-2-7b-hf并不可行，会导致比较差的实验结果。

**Comment by GarminQ** [comment]
感谢你的解答，我还以为是我不小心改动了一部分代码，导致产生了糟糕的结果
![image](https://github.com/user-attachments/assets/290894f0-cfe3-408a-a04d-799374857ad5)
所以现在的merge方法只适用于ΔW较小的情况，对吧？
合并论文中提到的NeuralBeagle14-7B 和 Turdus来构建 supermario v1是可行的吗？都是基于Beagle14-7B微调的

**Comment by yule-BUAA** [comment]
对的，现在的merge方法只适用于ΔW较小的情况。

论文中利用NeuralBeagle14-7B 和 Turdus来构建 supermario v1是可行的，因为相较于Beagle14-7B，它们由于微调产生的参数变化是比较小的。

**Comment by GarminQ** [comment]
非常感谢！在你的新工作中，我看到了更好的解决方案，good work！
