### ISSUE TITLE
请问task arthmetic在scaling_coefficient=1的设定下，是不是就等同于average merging了

### ISSUE THREAD

**Issue by yaokunkun** [yule-BUAA/MergeLM#42]
您好！我阅读了您MergingMethod里面的实现，我看到在按mask merging的逻辑里，是先进行了DARE把参数drop掉了，然后再调用task arthmetic的方法，而task arthmetic里面是
`merged_params[param_name] = pretrained_param_dict[param_name] + scaling_coefficient * self.task_vector_param_dict[param_name]`
相当于把delta参数乘以scaling_coefficient再加回backbone里。
如果它是1的话，是不是和average merging一样了？

**Comment by yule-BUAA** [comment]
嗨，
在我们的实现中，如果scaling_coefficient设置为```1/n```（其中n为要合并的模型的数量），那么task arithmetic就和average merging是一样的了。

**Comment by yaokunkun** [comment]
噢噢噢，我明白啦，谢谢你！
