### ISSUE TITLE
请问应该如何运行Dare+Ties

### ISSUE THREAD

**Issue by daidaiershidi** [yule-BUAA/MergeLM#43]
mask_apply_method只能选择"average_merging", "task_arithmetic"

**Comment by yule-BUAA** [comment]
嗨，

我们当前这个仓库中的TIES并不支持对LLM的合并（因为当前的TIES实现是遵照原始论文，从全局参数中统计最小量级的参数）。我们另一篇后续工作的代码库[MergeLLM](https://github.com/yule-BUAA/MergeLLM)中实现的TIES方法支持了合并LLM（最小量级参数的统计从全局变为了每个参数内部），所以要是想尝试DARE+TIES的话，可以使用[MergeLLM](https://github.com/yule-BUAA/MergeLLM)。

如果你的设备空间受限，那么可以考虑使用[mergekit](https://github.com/arcee-ai/mergekit)这个高效的模型合并库来减少内存需求，里面也集成了DARE+TIES方法。

**Comment by daidaiershidi** [comment]
> 嗨，
> 
> 我们当前这个仓库中的TIES并不支持对LLM的合并（因为当前的TIES实现是遵照原始论文，从全局参数中统计最小量级的参数）。我们另一篇后续工作的代码库[MergeLLM](https://github.com/yule-BUAA/MergeLLM)中实现的TIES方法支持了合并LLM（最小量级参数的统计从全局变为了每个参数内部），所以要是想尝试DARE+TIES的话，可以使用[MergeLLM](https://github.com/yule-BUAA/MergeLLM)。
> 
> 如果你的设备空间受限，那么可以考虑使用[mergekit](https://github.com/arcee-ai/mergekit)这个高效的模型合并库来减少内存需求，里面也集成了DARE+TIES方法。

请问论文中的Dare+Ties的实现，是Ties原本那种的实现方式，还是mergekit中逐层合并的方式？对于大模型，哪种实现方式更好啊

**Comment by yule-BUAA** [comment]
我们论文中的实现是逐个参数矩阵比较+合并的方式。对于大模型来说，统计全局的参数不太可行，所以我们选择了逐个参数比较来实现DARE+TIES。
