### ISSUE TITLE
Can models of different architectures be merged?

### ISSUE THREAD

**Issue by win10ogod** [yule-BUAA/MergeLM#7]
Can models of different architectures be merged?

**Comment by yule-BUAA** [comment]
Hi. Models with different architectures **cannot** be merged by existing model merging methods since they assume the models to be merged **are fine-tuned from the same architecture**. They merge parameters of multiple models so they need to guarantee the architecture of the models to be identical.

**Comment by win10ogod** [comment]
thank!
