### ISSUE TITLE
Is it possible to merge 2 LLAMA derive models like LLaVA and CodeLLAMA?

### ISSUE THREAD

**Issue by ramkumarkoppu** [yule-BUAA/MergeLM#9]
Does all the models have to be same modality? Is it possible to merge 2 LLAMA derive models like LLaVA and CodeLLAMA?

**Comment by yule-BUAA** [comment]
According to our experience, before merging two models, we can first check the range of SFT parameter changes in the two models. When the parameter range does not change much, directly merging two models is promising.

Please note that CodeLLAMA is additionally pre-trained based on Llama 2, whose parameter changed ranges are somewhat significant. This may make DARE or model merging methods fail. You can refer to section 4.6 in our paper for more discussions.

**Comment by yule-BUAA** [comment]
Close this issue now.

Please feel free to reopen it when there are any further questions.
